services:
  postgres:
    image: 'postgres:16.0'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=english'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
